# Default values for pdp-engine.

global:
  ep: localhost
  manager: storage-manager
  host: 0.0.0.0
  port: 5567
  debugMode: "'true'"

ports:
  http-manager:
    port: 5567
    targetPort: 5567
    type: TCP
  https-manager:
    port: 1025
    targetPort: 443
    type: TCP

ingress:
  path: /storage-manager

requests:
  serviceCpu: 4m
  serviceMemory: 70Mi
  dbCpu: 2m
  dbMemory: 70Mi

image: 
  imagePullPolicy: Never
  image: alvi:latest
persistence: 
  accessModes: ReadWriteMany
  dbStorageSize: 5Gi
  type: DirectoryOrCreate

# VolumeClaim values
volumeClaim:
  name: storage-manager-pvc
