apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-manager-config
data:
  HOST: {{ .Values.global.host | quote }}
  PORT: {{ .Values.global.port | quote }}
  DEBUG_MODE: {{ .Values.global.debugMode | quote }}
