apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-manager-config
data:
  AUTH_SERVER_URL: {{ .Values.global.host | quote }}
  PREFIX: {{ .Values.global.prefix | quote }}
  HOST: {{ .Values.global.host | quote }}
  PORT: {{ .Values.global.port | quote }}
