apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumeClaim.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    alvi_type: userman
spec:
  storageClassName: ""
  volumeName: {{ .Values.volumeClaim.name }}
  accessModes:
    - {{ .Values.persistence.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.dbStorageSize }}
  selector:
    matchLabels:
      alvi_type: userman
